### PR TITLE
Update for log.wien

### PR DESCRIPTION
**Pull request by davidschoefberger**

### CODE REVIEW

**Comment by tommy-hartmann** [comment]
Nice work! The login and `welcome()` works for me now.
Nevertheless the `profile()` function shows me an error:

```
{'Exception': 'API Gateway P encountered an error. Error Message: Resource /w/user/profile not found. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - null, Invocation Time:2:43:31 PM, Date:Dec 29, 2021,  Client IP - XXX.XXX.XXX.XXX, User - Default and Application:null'}
```

**Comment by davidschoefberger** [comment]
@tommy-hartmann you are right ... I forgot about that, since I'm not using the profile function. The unfortunate
thing is, that the profile function is still using the old API endpoint, so Wiener Netze did split that up. I will try to have a look on it in the next days.

**Comment by davidschoefberger** [comment]
Hi @tommy-hartmann,

I think I fixed it now. Can you check? The profil() function and the rest should work again. Looks like we now have to use the old and the new API endpoints ...

**Comment by tommy-hartmann** [comment]
Hi @davidschoefberger,

I tested most of the api calls and it works fine now including the profile function, thanks!
I hope this will be merged soon.

**Comment by mundschenk-at** [comment]
Any particular reason you closed this PR, @davidschoefberger?

**Pull request closed without merging**
